### ISSUE TITLE
Add polygon RPCs to wallet connect config

### ISSUE THREAD

**Issue by cazala** [decentraland/decentraland-connect#25]
Here: https://github.com/decentraland/decentraland-connect/blob/master/src/configuration.ts#L20

Otherwise you get this error when connected to Polygon: 

<img width="1054" alt="Screen Shot 2021-09-07 at 5 18 21 PM" src="https://user-images.githubusercontent.com/2781777/132406217-04dd7b8f-d6d0-4f80-a667-a60a4eb78496.png">

**Comment by nicosantangelo** [comment]
Done!
