### ISSUE TITLE
Evaluate WalletConnect2.0 when beta finished

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/decentraland-connect#26]
https://medium.com/walletconnect/walletconnect-cloud-is-live-72b8ce89e87c

# Update 1/30/2023
- [Migration notes](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0)
- [Blocked by web3-react](https://github.com/Uniswap/web3-react/issues/708)

**Comment by nachomazzara** [comment]
We need to migrate to 2.0 as 1.0 will be deprecated on 1st March

**Comment by LautaroPetaccio** [comment]
The migration was completed.
