### ISSUE TITLE
Research: Wallet Connect

### ISSUE THREAD

**Issue by braianj** [decentraland/decentraland-connect#40]

**Comment by nicosantangelo** [comment]
Can we get a bit more info in this issue? Just to see if it's related to #26, #20, #23, #17

**Comment by braianj** [comment]
The objective of the issue is to investigate how to obtain the uri that creates the WalletConnect library to generate the qrcode and thus be able to implement our own UI.
For this we are investigating the use of the proposal [EIP-1328 ](https://eips.ethereum.org/EIPS/eip-1328) and looking at the possibility of reusing some of the packages offered by WalletConnect.
This is the first task of several to see the possibilities of changing the UI of any of the possible options currently available for login.
As for the tasks mentioned above I think that with the use of [WalletConnect V2](https://github.com/decentraland/decentraland-connect/issues/26) this could be [easier](https://docs.walletconnect.com/2.0/javascript/sign/dapp-usage-standalone-client), but it is still in beta.
