### ISSUE TITLE
Formatic doesn't work

### ISSUE THREAD

**Issue by Tobiik** [decentraland/decentraland-connect#62]
When you press 'Formatic' nothing pop ups. Windows 10, Brave, shields disabled.

**Comment by fzavalia** [comment]
Can confirm the issue:

This is the error that is showing

![image](https://github.com/decentraland/decentraland-connect/assets/24811313/2ff71bfb-9db8-4340-a2ff-720c6e6cb2ca)

**Comment by LautaroPetaccio** [comment]
This issue was fixed.
